[build]
  functions = "functions"   # folder untuk serverless function
  publish = "."             # tidak ada frontend, publish root saja

[functions.unfollowers]
  runtime = "python3.11"   # runtime Python 3.11
